package config


const(
	LISTEN_PORT = "8080"
	PACK_DATA_SIZE_TYPE_LEN = 4    //int32
	MAX_PACK_DATA_SIZE = 1 << 4
	RING_BUFFER_SIZE = 2 * MAX_PACK_DATA_SIZE
	PACK_CHAN_SIZE = 100
	MAX_TCP_CONN = 1000000
)